### ISSUE TITLE
make components essentially progressive (service workers) in anticipation of push messaging

### ISSUE THREAD

**Issue by ReinsBrain** [rebelstackio/yakchat#43]
meeting criteria: https://developers.google.com/web/fundamentals/app-install-banners/#criteria

- [ ] The web app is not already installed.
and [prefer_related_applications](https://developers.google.com/web/fundamentals/app-install-banners/native) is not true.
- [ ] Includes a [web app manifest](https://developers.google.com/web/fundamentals/web-app-manifest/) that includes:
short_name or name
    - [ ] icons must include a 192px and a 512px sized icons
    - [ ] start_url
    - [ ] display must be one of: fullscreen, standalone, or minimal-ui
- [ ] Served over HTTPS (required for service workers)
- [ ] Has registered a service worker with a fetch event handler

When these criteria are met, will fire a beforeinstallprompt event that you can use to prompt the user to install your Progressive Web App, and may show a [mini-info bar](https://developers.google.com/web/fundamentals/app-install-banners/#mini-info-bar). See [Listen for beforeinstallprompt](https://developers.google.com/web/fundamentals/app-install-banners/#listen_for_beforeinstallprompt).

Helpers: https://github.com/GoogleChrome/workbox

**Comment by jegj** [comment]
@ReinsBrain  @pablolimo  @oreyes1991  Parcel is a pain in the ass .... it doesn't have a  good PWA support yet ....i just trying to connect the service worker with the build... the way parcel works with assets make really hard to pre-caches assets in the service worker( since the name  changes all the time... **main.21haha122.js**). i was able to set up push  notification but i think we should go back with webpack.... think parcel is good for smalls projects like the front-script

**Comment by jegj** [comment]
found something that can help to continue using parcel....

**Comment by jegj** [comment]
doesn't work .....  :angry:

**Comment by oreyes1991** [comment]
have you seen this?
https://github.com/parcel-bundler/parcel/issues/303#issuecomment-352216876

**Comment by oreyes1991** [comment]
yeah i see other people having trouble, we should go back to webpack

**Comment by jegj** [comment]
Closed ... new ticket required to go back to webpack
